### ISSUE TITLE
Translating new AMRs; format of input and encoding

### ISSUE THREAD

**Issue by SreehariSankar** [yanzhangnlp/LDGCNs#1]
Hello,
I would like to use this to convert AMR into text in the context of my own research.
Could you please specify what the format of my AMR data should be in and how to do the encoding so that I can use one of your pre-trained models to do the conversion?

Thanks!
Hari

**Comment by yanzhangnlp** [comment]
Hi Hari,

We use the same input format as previous work. For details,  please refer to the paper (modeling graph structure in transformer for better amr-to-text generation).

Also, you can refer to our preprocess folder for the preprocessing code and scripts. Here, to use the code, you need to get the AMR Sembank (e.g., LDC2017T10) first.

We will also upload our pre-trained models soon.

Regards,
Yan
